### ISSUE TITLE
make display faster

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/company-english-helper#1]
In my Emacs environment, company-english-helper need about 1.5 second to popup.
I have company-mode delay with:

```elisp
(setq         company-idle-delay .1
        company-tooltip-idle-delay 0.1)
```
I think the performance is not on company-mode isde, because I use CIDER for Clojure code completion can be faster. Almost immediately.

Maybe I can provide an Emacs `profiler` result?

**Comment by manateelazycat** [comment]
@stardiviner Default dict use 11w word, maybe your machine is not good enough.

Maybe you can use stardict.py translate your own litte dict for better performance?
