### ISSUE TITLE
The conflication between this package and the `global-company-mode`.

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/company-english-helper#10]
On Ubuntu 20.04, I'm currently using the following settings to trigger a drop-down menu for LaTeX commands with auctex:

```emacs-lisp
(use-package company)
(add-hook 'after-init-hook 'global-company-mode)
```
Now, I also installed `company-english-helper` through straight:

```emacs-lisp
(straight-use-package
 `(company-english-helper :type git :host github  :repo "manateelazycat/company-english-helper"))

(require 'company-english-helper)
```
After I execute command `toggle-company-english-helper', though  `company-english-helper` will work as described by you, but the completion of LaTeX commands by `global-company-mode` will be disabled.

Any hints for solving this problem?

Regards,
HY

**Comment by manateelazycat** [comment]
no，this package should turn on when you need it.

it can not works with other company backend

**Comment by hongyi-zhao** [comment]
> it can not works with other company backend

Why not let it can?

**Comment by manateelazycat** [comment]
> > it can not works with other company backend
> 
> Why not let it can?

no time

PR are welcome
