### ISSUE TITLE
How to show tooltip even after completion (or only one candidate) ?

### ISSUE THREAD

**Issue by panmengguan** [manateelazycat/company-english-helper#11]
感谢这个插件！想请教一下，能否进行配置，使得在补全完成，或者补全 candidate 仅有一个的时候，也能够显示 company-english-helper 的 tooltip，这样就在仍然能够看到单词的意思了，谢谢！

**Comment by manateelazycat** [comment]
> 感谢这个插件！想请教一下，能否进行配置，使得在补全完成，或者补全 candidate 仅有一个的时候，也能够显示 company-english-helper 的 tooltip，这样就在仍然能够看到单词的意思了，谢谢！

这个插件只是补全后端，你需要配置company-mode本身
