### ISSUE TITLE
translation are not aligned correctly

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/company-english-helper#2]
![image](https://user-images.githubusercontent.com/378699/44909615-9693eb00-ad52-11e8-941d-2df5a1837b15.png)

The right side translation is not correctly aligned.
I'm using the latest version through `use-package-quelpa`.
```elisp
(use-package company-english-helper
  :quelpa ((company-english-helper :fetcher github
                                   :repo "manateelazycat/company-english-helper")
           :upgrade t)
  ;; :load-path "~/Code/Emacs/company-english-helper/"
  :commands (toggle-company-english-helper)
  :init (dolist (hook '(org-mode-hook
                        git-commit-mode-hook
                        rcirc-mode-hook))
          (add-hook hook #'toggle-company-english-helper))
  )
```
- Emacs version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

**Comment by manateelazycat** [comment]
![image](https://user-images.githubusercontent.com/237487/45128456-bdb64680-b1b0-11e8-8e9b-f9faf24222ad.png)

Please use newest version and test bug with "emacs -Q"

It's seen something wrong in your font configuration.

**Comment by stardiviner** [comment]
@manateelazycat Which font do you using? I'm using "Hack" font.

**Comment by stardiviner** [comment]
I also tested font "DejaVu Sans Mono", still same result.

**Comment by manateelazycat** [comment]
In Mac i use Monaco
In Linux i use Droid Sans Mono

I believe it's a font configuration problem, not a bug of company-english-helper.

**Comment by stardiviner** [comment]
Me too. That's why I asked what font you use, I want to try the font you're using.
