### ISSUE TITLE
Doesn't work with below errors..

### ISSUE THREAD

**Issue by basheewang** [manateelazycat/company-english-helper#3]
Debugger entered--Lisp error: (args-out-of-range 0 114)
  put-text-property(0 114 mouse-face (company-tooltip-mouse) #(" likability                        n.﻿可﻿爱﻿．﻿．﻿．﻿．﻿..." 1 2 (:initials "n.可爱")))
  font-lock-append-text-property(0 114 mouse-face company-tooltip-mouse #(" likability                        n.﻿可﻿爱﻿．﻿．﻿．﻿．﻿..." 1 2 (:initials "n.可爱")))
  company-fill-propertize(#("likability" 0 1 (:initials "n.可爱")) "                        n.﻿可﻿爱﻿．﻿．﻿．﻿．﻿．﻿．﻿．﻿．﻿．﻿．..." 112 t " " " ")
  company--create-lines(0 10)
  company-pseudo-tooltip-show(1 2 0)
  company-pseudo-tooltip-show-at-point(6 3)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer asd> #<window 3 on asd> 6 6)
  apply(company-idle-begin (#<buffer asd> #<window 3 on asd> 6 6))
  timer-event-handler([t 23468 42728 226928 nil company-idle-begin (#<buffer asd> #<window 3 on asd> 6 6) nil 197000])

**Comment by manateelazycat** [comment]
Please test with "emacs -Q" 

Please let me know "emacs -Q" still have this issue

**Comment by manateelazycat** [comment]
I can't reproduce this problem, sorry.

**Comment by basheewang** [comment]
I am sorry for later response. The error are due to some weird config from my .emacs file. Now fixed and worked as a charm. :)
