### ISSUE TITLE
能否自动加上空格

### ISSUE THREAD

**Issue by LuoPX-15510486969** [manateelazycat/company-english-helper#4]
enter选中候选词上屏后能否自动加上空格呢？因为既然是英文输入，选中的候选词肯定是一个完整的单词，后面跟上空格省得每次选中上屏后再按一次空格接着下一次的输入

**Comment by manateelazycat** [comment]
这个插件只是提供了英文词典的后端, 要自动加空格请折腾 company 这个插件, 你的要求无法在本项目中实现.

**Comment by stardiviner** [comment]
`company-backend` can implement this just like some backends like irony provide parentheses auto fill etc.

**Comment by stardiviner** [comment]
`company-backend` can implement this just like some backends like irony provide parentheses auto fill etc.
