### ISSUE TITLE
Not working with doom emacs

### ISSUE THREAD

**Issue by showgood** [manateelazycat/company-english-helper#6]
在我的doom emacs中配置如下：
```
(package! company-english-helper :recipe (:host github :repo "manateelazycat/company-english-helper"))

(use-package! company-english-helper)
```

之后在编辑文件的时候运行 toggle-company-english-helper, 但是在company-backends 变量里没有 company-english-helper-search， 之后补全就不工作

**Comment by manateelazycat** [comment]
我从来不用 use-package, use-package 需要你自己折腾。

**Comment by showgood** [comment]
改用了你readme里面的方式，还是不工作。。。

**Comment by manateelazycat** [comment]
你先 emacs -Q 然后做一个横向对比，看看是不是你配置文件的问题。
