### ISSUE TITLE
我在尝试转换几个词典

### ISSUE THREAD

**Issue by longlu** [manateelazycat/company-english-helper#9]
但是词语解释进不去？
我把编辑 stardict xml词典文件 把html tag 去掉了，把所有解释弄到一行上，但是转换后的结果上词语解释没进去

**Comment by manateelazycat** [comment]
没看懂你说的啥，如果你用的是正常格式的字典，你可以按照README的方法来做词典转换。

**Comment by longlu** [comment]
比如
`<key>abactinal</key>

<definition type="h">
<![CDATA[a.1: Zool. Remote from the actinal area; pertaining to that part of the surface of a radiated animal which is opposite to the mouth, e.g. the apex of a sea-urchin, or upper surface of a star-fish. See actinal.]]>
</definition>
</article>

<article>
<key>abaction</key>

<definition type="h">
<![CDATA[1: rare. A driving away, as of cattle. (In Cockeram 1626, and some mod. Dict., but perhaps never in general use.)]]>
</definition>
</article>

<article>
<key>abactor</key>

<definition type="h">
<![CDATA[1: Obs. ‘One who drives away or steals cattle in herds, or great numbers at once, in distinction from those that steal only a sheep or two.’ J.]]>
</definition>
</article>

<article>
<key>abaculus</key>

<definition type="h">
<![CDATA[1: Arch. = abaciscus. — Fairholt.]]>
</definition>
</article>

<article>
<key>abacus</key>

<definition type="h">
<![CDATA[1: †1. A board or tray strewn with sand, for the delineation of figures, geometrical diagrams, etc. Obs. 2. A calculating table, or frame; spec. one in which balls slide upon wires, and gen. any arrangement for the mechanical solution of arithmetical problems. 3. Arch. The upper member of the capital of a column, supporting the architrave; in the Tuscan, Doric, and ancient Ionic orders, a square flat plate, but in the Corinthian and Composite, variously cut and ornamented. †4. = aback n. Obs. (perh. never used in Eng.) 5. Gr. &.Rom. Antiq. A side-board.]]>
</definition>
</article>

<article>
<key>abad</key>

<definition type="h">
<![CDATA[1: obs. forms of abode n. and v.]]>
</definition>
</article>

<article>
<key>abada</key>

<definition type="h">
<![CDATA[1: Obs. An early name for the Rhinoceros.]]>
</definition>
</article>

<article>
<key>Abaddon</key>

<definition type="h">
<![CDATA[1: Used in Rev.. ix. 11 as equivalent to the Gr. +pokkÊxm, destroyer, as the name of ‘the angel of the bottomless pit.’ Hence applied by Milton to the bottomless pit, or abyss of hell, itself.]]>
</definition>
</article>

<article>
<key>abade</key>

<definition type="h">
<![CDATA[1: obs. forms of abode n. and v.2: obs. form of abode n. and v.]]>
</definition>
</article>

<article>
<key>abaft</key>

<definition type="h">
<![CDATA[adv. and prep.1: A. adv. †1. Of direction: backwards. Obs. 2. Of position: literally, back, behind, in the rear. From an early period, it seems to have been confined to a ship (in reference to which its immediate source baft is also found in the 14th c.); the bows are the foremost, and the stern the aftermost part, hence abaft means ‘In the after part or stern half of the ship.’ 3. By extension from the nautical term. B. prep. [The adv. defined by an object.] In the rear of, behind. Only in nautical lang., with reference to a ship or any specified part of her.]]>
</definition>
</article>

<article>
<key>abaht</key>

<definition type="h">
<![CDATA[1: repr. dial. and colloq. pronunc. of about adv. and prep.]]>
</definition>
</article>`

是可以转换，但是词语的解释没转换进去，只有词语本身

**Comment by longlu** [comment]
`<article>`

`<key>abacus</key>`

`<definition type="h">`
`<![CDATA[1: †1. A board or tray strewn with sand, for the delineation of figures, geometrical diagrams, etc. Obs. 2. A calculating table, or frame; spec. one in which balls slide upon wires, and gen. any arrangement for the mechanical solution of arithmetical problems. 3. Arch. The upper member of the capital of a column, supporting the architrave; in the Tuscan, Doric, and ancient Ionic orders, a square flat plate, but in the Corinthian and Composite, variously cut and ornamented. †4. = aback n. Obs. (perh. never used in Eng.) 5. Gr. &.Rom. Antiq. A side-board.]]>
</definition>`
`</article>`

`<article>`
`<key>abad</key>`

`<definition type="h">`
`<![CDATA[1: obs. forms of abode n. and v.]]>`
`</definition>`
`</article>`

**Comment by longlu** [comment]
我在看怎么样编辑xml源文件能全部转换进去

**Comment by longlu** [comment]
`<article>`
`<key>aborticide</key>`

`<definition type="h">`
`<![CDATA[noun-[əbɔrtɪsɪd /-bɔː-]-killing of a fetus while it is in the womb]]>`
`</definition>`
`</article>`

`<article>`
`<key>abortifacient</key>`
`<synonym>abortifacients</synonym>`

`<definition type="h">`
`<![CDATA[noun-[-tɪ'feɪʃənt]-drug which causes abortion, agent which causes the premature termination of a pregnancy]]>`
`</definition>`
`</article>`

`<article>`

**Comment by longlu** [comment]
`<article>`
`<key>abandonment</key>`

`<definition type="x">`
`<![CDATA[<k>abandonment</k>`
`<blockquote><abr>n</abr></blockquote>`
`<blockquote><b>1</b> <c c="darkgray">DESERTION</c>, <c c="gray">leaving (behind), neglect, marooning, stranding</c></blockquote>`
`<blockquote><blockquote><b><c c="black">FORMAL</c></b> <c c="gray">forsaking, decampment, dereliction</c></blockquote></blockquote>`
`<blockquote><blockquote><b><c c="black">COLLOQ.</c></b> <c c="gray">running out on, jilting, ditching</c></blockquote></blockquote>`
`<blockquote><b>2</b><c c="darkblue"><ex> abandonment of an activity </ex></c></blockquote>`
`<blockquote><blockquote><c c="gray">giving-up, stopping, resignation (from), surrender, waiving, sacrifice</c></blockquote></blockquote>`
`<blockquote><blockquote><b><c c="black">FORMAL</c></b> <c c="gray">renunciation, relinquishment, cessation, discontinuation, discontinuance, abdication, cession</c></blockquote></blockquote>`
`<blockquote><blockquote><b><c c="black">COLLOQ.</c></b> <c c="gray">dropping, scrapping, ditching</c></blockquote></blockquote>]]>`
`</definition>`
`</article>`

**Comment by longlu** [comment]
可以了，这下我知道了
不过，如果解释很长的话，好像 company 只显示了一行。

在init.el   里面试了下加了这个
(setq company-english-helper-candidate-max-width 1000)
没用。
